import Link from "next/link";
import { ContentForm } from "@/components/content-form";
import { requireStaff } from "@/lib/auth";
export default async function NewContentPage({searchParams}:{searchParams:Promise<{type?:string;title?:string;slug?:string;agentKey?:string;category?:string;paths?:string}>}) {
  const staff = await requireStaff(); const params=await searchParams; const type=params.type === "onboarding" ? "onboarding" : "article";
  const fromCurriculum = type === "onboarding" && Boolean(params.title && params.slug);
  const metadata = fromCurriculum ? { objective:params.title, proposalSignals:[params.title], expectedPages:(params.paths ?? "").split("|").filter(Boolean), qualificationQuestions:[], successCriteria:[], branches:[], fallbacks:[], actionSteps:[], sourceMetadata:{origin:"limova_code_inventory", sourcePaths:["Limova-2-0/client@main", "Limova-2-0/api@main"]} } : undefined;
  return <><span className="eyebrow">Nouveau contenu</span><h1 className="page-title">Donner un nouveau repère à Charly</h1><div className="actions"><Link className={`button ${type==="article"?"primary":"secondary"}`} href="/studio/contenus/nouveau?type=article">Article</Link><Link className={`button ${type==="onboarding"?"primary":"secondary"}`} href="/studio/contenus/nouveau?type=onboarding">Parcours</Link></div><div style={{height:18}}/><div className="editor-layout"><section className="editor-card card"><ContentForm defaults={{ ownerEmail: staff.email, type, title:params.title, slug:params.slug, agentKey:params.agentKey, categorySlug:params.category, summary:fromCurriculum ? `Accompagner le membre pour ${params.title?.toLocaleLowerCase("fr")}.` : undefined, bodyMarkdown:fromCurriculum ? `## Objectif\n\n${params.title}\n\n## Ce que le code permet de préremplir\n\nLes pages concernées sont proposées ci-dessous. Le staff doit confirmer les règles métier et démontrer le parcours réel.\n\n## Étapes\n\nÀ compléter par une démonstration dans Limova.` : undefined, metadata }}/></section><aside className="publication-rail card"><span className="eyebrow">Publication</span><div style={{height:18}}/><div className="rail-step active">Brouillon</div><div className="rail-step">À valider</div><div className="rail-step">Publié</div><div className="rail-step">Archivé</div></aside></div></>;
}
