export const GOLDEN_QUERIES = [
  { query:"De quoi mes agents sont-ils capables avec Gmail ?",slug:"de-quoi-sont-capables-mes-agents-avec-gmail",path:"/integrations" },
  { query:"Que peut faire un agent avec Google Drive ?",slug:"de-quoi-sont-capables-mes-agents-avec-google-drive",path:"/integrations" },
  { query:"Que peuvent faire mes agents avec Google Calendar ?",slug:"de-quoi-mes-agents-sont-ils-capables-avec-google-calendar",path:"/integrations" },
  { query:"Comment connecter Outlook Mail ?",slug:"de-quoi-mes-agents-sont-ils-capables-avec-outlook-mail",path:"/integrations" },
  { query:"Pourquoi mon compte Outlook ne se connecte pas ?",slug:"impossible-de-connecter-un-compte-outlook",path:"/integrations" },
  { query:"Que peuvent faire mes agents avec HubSpot ?",slug:"que-peuvent-faire-mes-agents-avec-hubspot",path:"/integrations" },
  { query:"Comment utiliser WhatsApp Business avec mes agents ?",slug:"que-peuvent-faire-mes-agents-avec-whatsapp-business",path:"/integrations" },
  { query:"Comment connecter Slack ?",slug:"que-peuvent-faire-mes-agents-avec-slack",path:"/integrations" },
  { query:"Comment connecter Shopify ?",slug:"que-peuvent-faire-mes-agents-avec-shopify",path:"/integrations" },
  { query:"Que peut faire Limova avec Notion ?",slug:"que-peuvent-faire-mes-agents-avec-notion",path:"/integrations" },
  { query:"Que peuvent faire mes agents avec Google Sheets ?",slug:"de-quoi-sont-capables-mes-agents-avec-google-sheets",path:"/integrations" },
  { query:"Comment connecter Google Docs ?",slug:"que-peuvent-faire-mes-agents-avec-google-docs",path:"/integrations" },
  { query:"Comment connecter Calendly ?",slug:"que-peuvent-faire-mes-agents-avec-calendly",path:"/integrations" },
  { query:"Comment connecter mes outils à Limova ?",slug:"connectez-vos-outils",path:"/integrations" },
  { query:"Pourquoi une intégration ne fonctionne pas ?",slug:"problemes-dintegrations",path:"/integrations" },
  { query:"Comment créer une campagne de prospection LinkedIn ?",slug:"creer-une-campagne-linkedin-avec-elio",path:"/super-powers" },
  { query:"Comment automatiser ma prospection LinkedIn ?",slug:"prospection-linkedin-automatisee-agent-ia",path:"/super-powers" },
  { query:"Comment créer une campagne d'appels ?",slug:"creer-une-campagne-dappels-avec-elio",path:"/super-powers" },
  { query:"Comment publier un post avec John ?",slug:"creer-un-post-avec-john",path:"/super-powers" },
  { query:"Comment automatiser mes réseaux sociaux ?",slug:"publier-contenu-reseaux-sociaux-agent-ia",path:"/super-powers" },
  { query:"Comment créer une image avec John ?",slug:"creer-une-image-avec-john",path:"/super-powers" },
  { query:"Comment générer une vidéo avec John ?",slug:"generer-une-video-avec-john",path:"/super-powers" },
  { query:"Comment créer un article de blog ?",slug:"creer-un-article-de-blog-avec-lou",path:"/super-powers" },
  { query:"Comment créer un agent de support client ?",slug:"creer-un-agent-de-support-client-avec-tom",path:"/agents" },
  { query:"Comment créer un standard téléphonique ?",slug:"creer-un-agent-de-standard-telephonique-avec-tom",path:"/agents" },
  { query:"Qui est Charly ?",slug:"charly",path:"/agents" },
  { query:"Quelles tâches déléguer à un agent IA ?",slug:"10-taches-deleguer-agent-ia",path:"/agents" },
  { query:"Comment discuter avec mes agents ?",slug:"discuter-avec-vos-agents",path:"/agents" },
  { query:"Comment ajouter mes documents ?",slug:"ajoutez-vos-documents",path:"/documents" },
  { query:"Où retrouver mes campagnes et contenus ?",slug:"ou-retrouver-mes-contenus-campagnes-et-agents",path:"/" },
  { query:"Comment inviter un collaborateur ?",slug:"invitez-vos-collaborateurs",path:"/settings" },
  { query:"Comment ajouter un membre à mon équipe ?",slug:"ajouter-un-collaborateur",path:"/settings" },
  { query:"Comment configurer mes préférences de compte ?",slug:"configurez-votre-abonnement",path:"/settings" },
  { query:"Que faire après un échec de paiement ?",slug:"echec-de-paiement",path:"/settings/billing" },
  { query:"Comment fonctionne la facturation ?",slug:"facturation-et-abonnement",path:"/settings/billing" },
  { query:"Mes conversations sont vides, que faire ?",slug:"conversations-vides",path:"/conversations" },
  { query:"La page Limova ne se charge pas",slug:"le-site-page-ne-se-charge-pas",path:"/" },
  { query:"Je n'arrive pas à me connecter",slug:"impossible-de-se-connecter",path:"/login" },
  { query:"Comment Limova protège mes données ?",slug:"securite-des-donnees",path:"/settings" },
  { query:"Où trouver les questions fréquentes ?",slug:"questions-frequentes",path:"/" },
] as const;
