export type CurriculumJourney = {
  group: string;
  title: string;
  agentKey: "charly" | "elio" | "john" | "lou" | "tom" | "common";
  categorySlug: "bien-demarrer" | "super-pouvoirs" | "agents" | "integrations" | "compte-equipe" | "facturation" | "depannage";
  paths: string[];
};

const journeys = (group: string, agentKey: CurriculumJourney["agentKey"], categorySlug: CurriculumJourney["categorySlug"], paths: string[], titles: string[]) =>
  titles.map((title): CurriculumJourney => ({ group, title, agentKey, categorySlug, paths }));

const workspaceRoot = "/organizations/[organizationId]/workspaces/[workspaceId]";

export const LIMOVA_CURRICULUM: CurriculumJourney[] = [
  ...journeys("Accès et premiers pas", "charly", "bien-demarrer", ["/auth", "/auth/create-account", "/auth/verify-otp", "/accept-invitation/[token]", "/organizations/new", "/organizations/[organizationId]/onboarding/[step]", `${workspaceRoot}/chat`], ["Se connecter par code à usage unique", "Créer son compte Limova", "Accepter ou refuser une invitation", "Créer et configurer son organisation", "Choisir une offre et terminer le paiement", "Créer son premier espace de travail", "Changer d’espace de travail", "Se repérer dans la navigation Limova", "Choisir un assistant et démarrer une conversation", "Récupérer un compte sans organisation ou espace accessible"]),
  ...journeys("Compte, organisation et équipe", "common", "compte-equipe", ["/account", "/account/profile", "/account/preferences", "/account/security", "/organizations/[organizationId]/company", "/organizations/[organizationId]/members", `${workspaceRoot}/settings`, `${workspaceRoot}/settings/members`], ["Modifier son profil et sa photo", "Changer et confirmer son adresse e-mail", "Modifier la langue et le fuseau horaire", "Gérer le consentement analytique", "Modifier les informations et le logo de l’entreprise", "Inviter un membre dans l’organisation", "Modifier le rôle d’un membre ou annuler son invitation", "Retirer un membre de l’organisation", "Créer, renommer et supprimer un espace de travail", "Ajouter ou retirer les membres d’un espace", "Comprendre les rôles, la visibilité et la propriété"]),
  ...journeys("Abonnement, crédits, API et téléphonie", "common", "facturation", ["/organizations/[organizationId]/billing/(settings)", "/organizations/[organizationId]/api", "/organizations/[organizationId]/phone-numbers", "/organizations/[organizationId]/charly-plus"], ["Consulter son offre, ses quotas et son utilisation", "Télécharger une facture et gérer le moyen de paiement", "Changer, annuler ou réactiver son offre", "Résoudre un accès bloqué par le paiement ou les quotas", "Acheter des crédits téléphoniques", "Configurer la recharge automatique des crédits", "Acheter et suivre ses crédits API", "Créer et administrer une clé API", "Activer la téléphonie", "Ajouter et configurer un numéro entrant", "Ajouter un numéro sortant et le vérifier", "Reconfigurer ou supprimer un numéro de téléphone"]),
  ...journeys("Assistants et conversations", "charly", "agents", [`${workspaceRoot}/assistants`, `${workspaceRoot}/assistants/history`, `${workspaceRoot}/assistants/my-assistants`, `${workspaceRoot}/chat`, `${workspaceRoot}/conversations/[conversationId]`], ["Choisir le bon assistant Limova", "Démarrer et retrouver une conversation", "Filtrer, renommer et supprimer une conversation", "Joindre un document ou un dossier à une conversation", "Modifier la visibilité d’une conversation", "Créer un assistant depuis une conversation", "Utiliser la mémoire de Charly", "Créer et gérer une routine planifiée", "Lancer une recherche web approfondie", "Générer un document depuis une conversation", "Analyser des données tabulaires", "Reprendre une génération longue ou interrompue"]),
  ...journeys("Documents et contexte", "common", "bien-demarrer", [`${workspaceRoot}/documents`, `${workspaceRoot}/conversations/[conversationId]`, `${workspaceRoot}/agents/[autonomousagentsId]`], ["Importer et traiter un document", "Créer et gérer un dossier", "Rechercher et déplacer un document", "Prévisualiser et télécharger un document", "Retraiter un document en erreur", "Télécharger un dossier en archive", "Gérer le contexte documentaire par défaut", "Attacher une source à un assistant autonome", "Distinguer retrait du contexte et suppression de la bibliothèque"]),
  ...journeys("Intégrations", "common", "integrations", [`${workspaceRoot}/integrations`, `${workspaceRoot}/integrations/catalog`, `${workspaceRoot}/integrations/connected-accounts`, `${workspaceRoot}/integrations/oauth-callback`, "/oauth/[network]/callback"], ["Rechercher une intégration dans le catalogue", "Connecter une intégration OAuth", "Connecter Gmail, Drive, Sheets ou Calendar", "Connecter Outlook ou un calendrier compatible", "Connecter LinkedIn pour prospecter ou publier", "Connecter Facebook ou Instagram", "Connecter Axonaut par clé API", "Connecter et configurer un CMS", "Renommer et partager un compte connecté", "Déconnecter ou reconnecter une intégration", "Résoudre une fenêtre OAuth bloquée ou refusée"]),
  ...journeys("Power-ups et contenus", "john", "super-pouvoirs", [`${workspaceRoot}/power-ups`, `${workspaceRoot}/content`, `${workspaceRoot}/content/drafts`, `${workspaceRoot}/content/finalized`, `${workspaceRoot}/campaigns/[campaignId]/social-media-posts`], ["Trouver le bon power-up", "Enregistrer, reprendre ou supprimer un brouillon", "Créer une image avec John", "Retirer l’arrière-plan d’une image", "Générer et télécharger une vidéo", "Générer et reprendre une présentation", "Transcrire un fichier audio", "Générer un média", "Créer et planifier un post social", "Créer une campagne de publications sociales", "Retrouver ses contenus et brouillons", "Utiliser le calendrier de publication"]),
  ...journeys("Blog et SEO", "lou", "super-pouvoirs", [`${workspaceRoot}/power-ups`, `${workspaceRoot}/campaigns/[campaignId]/blog`, `${workspaceRoot}/content`], ["Réaliser un audit SEO", "Générer un article de blog", "Créer une campagne d’articles de blog", "Piloter les articles d’une campagne blog", "Publier un article vers un CMS connecté"]),
  ...journeys("Campagnes de prospection", "elio", "super-pouvoirs", [`${workspaceRoot}/campaigns`, `${workspaceRoot}/campaigns/drafts`, `${workspaceRoot}/campaigns/active`, `${workspaceRoot}/campaigns/archived`, `${workspaceRoot}/campaigns/[campaignId]/linkedin`, `${workspaceRoot}/campaigns/[campaignId]/outbound-call`], ["Créer et modifier une campagne LinkedIn", "Démarrer, suspendre ou archiver une campagne LinkedIn", "Consulter les prospects, messages et statistiques LinkedIn", "Créer et modifier une campagne d’appels sortants", "Tester, démarrer ou suspendre une campagne d’appels", "Consulter les appels, transcriptions et résultats", "Comprendre et filtrer les statuts de campagne"]),
  ...journeys("Agents autonomes et canaux", "tom", "agents", [`${workspaceRoot}/agents`, `${workspaceRoot}/agents/drafts`, `${workspaceRoot}/agents/active`, `${workspaceRoot}/agents/archived`, `${workspaceRoot}/agents/[autonomousagentsId]`, `${workspaceRoot}/agents/phone/[phoneAgentId]`], ["Créer un agent de support", "Créer un agent téléphonique", "Modifier, tester, activer ou archiver un agent", "Ajouter des connaissances et intégrations à un agent", "Tester et publier le widget web", "Configurer le widget et ses domaines autorisés", "Connecter et diagnostiquer WhatsApp", "Traiter une conversation dans la boîte de réception", "Consulter les appels entrants et leurs transcriptions", "Créer et attribuer des étiquettes"]),
  ...journeys("Blocages et garde-fous", "common", "depannage", ["/"], ["Expliquer une restriction de rôle, d’offre ou de crédits", "Réagir à une page modifiée ou une cible ambiguë", "Reprendre après une erreur réseau ou un résultat absent", "Protéger les secrets et informations sensibles", "Confirmer une action à conséquence importante", "Passer la main au staff avec le bon contexte"]),
];

export function curriculumSlug(title: string) {
  return title.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase()
    .replace(/[’']/g, "-").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 160);
}
