import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import { eq } from "drizzle-orm";
import { createSavTestDb } from "../../../test/sav-db";
import { auditLogs, savActions, savAgentRuns, savDecisions, savMailboxes, savMessages, savProposalReviews, savReviewedReplayCases, savReviewedReplayRuns, savThreads } from "@/db/schema";
import { activateSavV0Cutover } from "./cutover";
import { decryptSavPayload, encryptSavPayload } from "./crypto";
import { getSavV0Dashboard, recordSavDeploymentDecision, summarizeSavV0Runs, type MetricRun } from "./metrics";
import { createReviewedSavReplay, runReviewedSavRuleReplay } from "./reviewed-replay";
import { savStructuredProposalSchema } from "./proposal";
import { savRunProvenance } from "./config";
const state = vi.hoisted(() => ({ db: null as unknown }));
vi.mock("@/db", () => ({ requireDb: () => state.db }));
let fixture: Awaited<ReturnType<typeof createSavTestDb>>;
let reviewId: string;
let messageId: string;
let runId: string;
const sha = "a".repeat(40);
const proposal = savStructuredProposalSchema.parse({ schemaVersion: 1, category: "billing", urgency: "normal", decision: { kind: "ticket_pending", reasonCode: "test", explanation: "Demande fictive pour le contrôle", confidence: 1_000 }, routing: { kind: "new", reason: "test", contactId: "21" }, ticket: { title: "Factures", description: "Client Alice, secret@example.com, 0612345678" }, process: [{ kind: "human_review", label: "Vérifier le cas fictif", sourceIds: [] }], replyDraft: "Brouillon fictif", internalNote: null, sources: [], knowledgeRevision: "kb-fixture", model: "fixture" });
const dimensions = { classification: "correct", routing: "correct", grounding: "correct", tone: "correct", escalation: "correct" };
beforeAll(async () => { fixture = await createSavTestDb(); state.db = fixture.db; }, 30_000);
afterAll(async () => { await fixture.client.close(); });
afterEach(() => { vi.unstubAllEnvs(); vi.unstubAllGlobals(); });
beforeEach(async () => {
  vi.stubEnv("SAV_ENCRYPTION_KEY_V1", "test-only-sav-metrics-encryption-key-32-characters");
  vi.stubEnv("SAV_CODE_REVISION", sha);
  await fixture.client.exec("TRUNCATE sav.mailboxes CASCADE; TRUNCATE sav.sync_state; TRUNCATE sav.reviewed_replay_runs; TRUNCATE sav.deployment_reviews; TRUNCATE audit_logs");
  const [mailbox] = await fixture.db.insert(savMailboxes).values({ email: "contact@limova.ai" }).returning();
  await activateSavV0Cutover({ receivedAfter: "2026-10-02T12:00:00Z", mailboxEmail: mailbox.email, intakeRecipient: "contact@limova.ai", deploymentSha: sha, activatedBy: "ugo@limova.ai" });
  const [thread] = await fixture.db.insert(savThreads).values({ mailboxId: mailbox.id, gmailThreadId: "metric-fixture", customerEmail: "secret@example.com", subject: "Factures" }).returning();
  const [message] = await fixture.db.insert(savMessages).values({ mailboxId: mailbox.id, threadId: thread.id, direction: "inbound", fromEmail: thread.customerEmail, bodyCiphertext: encryptSavPayload({ text: "Original client Alice à ne jamais copier" }), receivedAt: new Date("2026-10-02T12:01:00Z"), analysisStatus: "done" }).returning(); messageId = message.id;
  const [run] = await fixture.db.insert(savAgentRuns).values({ messageId, runtime: "google_adk", mode: "on", status: "succeeded", model: "fixture", promptRevision: "fixture-v1", inputHash: "fixture", codeRevision: sha, dataOrigin: "real", knowledgeRevision: proposal.knowledgeRevision, confidence: 1_000, proposalCiphertext: encryptSavPayload(proposal) }).returning(); runId = run.id;
  const [decision] = await fixture.db.insert(savDecisions).values({ messageId, agentRunId: run.id, kind: "ticket_pending", reasonCode: "fixture", explanation: "Demande fictive", confidence: 1_000 }).returning();
  const [review] = await fixture.db.insert(savProposalReviews).values({ messageId, decisionId: decision.id, agentRunId: run.id, revision: 1, status: "approved", verdict: "correct", dimensions, beforeCiphertext: encryptSavPayload(proposal), afterCiphertext: encryptSavPayload(proposal), commentCiphertext: encryptSavPayload({ text: "Revue fictive" }), reviewedBy: "ugo@limova.ai" }).returning(); reviewId = review.id;
});
const replayInput = () => ({ reviewId, title: "Retrouver des factures", scenario: "Comment retrouver mes factures dans le produit ? Cas secret@example.com et 0612345678 https://exemple.invalid/client/123", expectedKind: "ticket_pending", requiresHumanApproval: false, anonymizationConfirmed: true });
describe("V0 metrics, reviewed replays and documentary deployment decisions", () => {
  it("never mixes versions, categories, simulations and real data", () => {
    const row: MetricRun = { id: "test", model: "fixture", promptRevision: "p1", knowledgeRevision: "k1", codeRevision: sha, dataOrigin: "real", runtime: "google_adk", category: "billing", status: "succeeded", confidence: 1_000, verdict: "correct", dimensions, errorCode: null };
    const groups = summarizeSavV0Runs([row, { ...row, runtime: "local_fixture" }, { ...row, promptRevision: "p2" }, { ...row, category: "how_to" }, { ...row, dataOrigin: "test" }]);
    expect(groups).toHaveLength(5);
    expect(groups.find((g) => g.version.origin === "simulation")?.reviewed).toBe(1);
    expect(summarizeSavV0Runs([{ ...row, verdict: null, dimensions: null }])[0].calibrationError).toBeNull();
    expect(summarizeSavV0Runs([{ ...row, confidence: null }])[0].calibrationError).toBeNull();
  });
  it("classifies production pilot runs as simulations and never invents a code version", () => {
    vi.stubEnv("NODE_ENV", "production"); vi.stubEnv("SAV_TEST_MODE", "false");
    expect(savRunProvenance(true)).toMatchObject({ dataOrigin: "simulation", codeRevision: sha });
    expect(savRunProvenance()).toMatchObject({ dataOrigin: "real" });
    vi.stubEnv("SAV_TEST_MODE", "true"); vi.stubEnv("SAV_CODE_REVISION", "uncommitted");
    expect(savRunProvenance()).toEqual({ dataOrigin: "test", codeRevision: "unknown" });
  });
  it("excludes old emails and retains original critical verdicts after human correction", async () => {
    await fixture.db.update(savProposalReviews).set({ verdict: "critical", dimensions: { ...dimensions, grounding: "critical" } }).where(eq(savProposalReviews.id, reviewId));
    let data = await getSavV0Dashboard();
    expect(data.versions[0].verdicts.critical).toBe(1);
    expect(data.versions[0].gate.eligible).toBe(false);
    expect(data.versions[0].gate.reasons).toContain("SAV_PROMOTION_HAS_CRITICAL_REVIEW");
    await fixture.db.update(savMessages).set({ receivedAt: new Date("2026-10-02T11:59:59Z") }).where(eq(savMessages.id, messageId));
    data = await getSavV0Dashboard();
    expect(data.versions).toHaveLength(0);
    expect(data.ingestion).toHaveLength(0);
  });
  it("requires Ugo and explicit anonymization; never copies the source mail or calls external APIs", async () => {
    const network = vi.fn(); vi.stubGlobal("fetch", network);
    await expect(createReviewedSavReplay(replayInput(), "reouven@limova.ai")).rejects.toThrow("SAV_REPLAY_UGO_REQUIRED");
    await expect(createReviewedSavReplay({ ...replayInput(), anonymizationConfirmed: false }, "ugo@limova.ai")).rejects.toThrow();
    await createReviewedSavReplay(replayInput(), "ugo@limova.ai");
    const [row] = await fixture.db.select().from(savReviewedReplayCases);
    const testCase = decryptSavPayload<{ input: { body: string } }>(row.caseCiphertext);
    expect(testCase.input.body).not.toMatch(/secret@example.com|0612345678|https:\/\/|Alice|Original/);
    const first = await runReviewedSavRuleReplay("ugo@limova.ai");
    const second = await runReviewedSavRuleReplay("ugo@limova.ai");
    const runs = await fixture.db.select().from(savReviewedReplayRuns);
    expect(runs.find((r) => r.id === first.id)).toMatchObject({ total: 1, failed: 0, result: { regression: null, scope: "deterministic_rules_only" } });
    expect(runs.find((r) => r.id === second.id)?.result).toMatchObject({ regression: false, baselineId: first.id });
    expect(network).not.toHaveBeenCalled();
  });
  it("reports failing rules and blocks promotion instead of presenting the replay as agent quality", async () => {
    await createReviewedSavReplay({ ...replayInput(), scenario: "Je souhaite parler à un humain pour retrouver mes factures" }, "ugo@limova.ai");
    await runReviewedSavRuleReplay("ugo@limova.ai");
    const data = await getSavV0Dashboard();
    expect(data.replayHistory[0].failed).toBe(1);
    expect(data.versions[0].gate.reasons).toContain("SAV_V0_REPLAY_FAILED");
    await expect(recordSavDeploymentDecision({ snapshotHash: data.snapshotHash, versionId: data.versions[0].id, decision: "request_promotion", reason: "Demande fictive qui doit rester bloquée" }, "ugo@limova.ai")).rejects.toThrow("SAV_DEPLOYMENT_GATE_BLOCKED");
  });
  it("records only Ugo's documentary hold decision with exact evidence and detects stale reviews", async () => {
    const data = await getSavV0Dashboard();
    const request = { snapshotHash: data.snapshotHash, versionId: data.versions[0].id, decision: "hold", reason: "Continuer la recette réelle avant toute demande de pilote" };
    await expect(recordSavDeploymentDecision(request, "contact@limova.ai")).rejects.toThrow("SAV_DEPLOYMENT_UGO_REQUIRED");
    await recordSavDeploymentDecision(request, "ugo@limova.ai");
    expect((await getSavV0Dashboard()).decisions[0]).toMatchObject({ decision: "hold", reason: request.reason });
    expect(await fixture.db.select().from(savActions)).toHaveLength(0);
    expect((await fixture.db.select().from(auditLogs)).some((r) => r.action === "sav_deployment_decision_recorded")).toBe(true);
    await fixture.db.update(savAgentRuns).set({ status: "fallback" }).where(eq(savAgentRuns.id, runId));
    await expect(recordSavDeploymentDecision(request, "ugo@limova.ai")).rejects.toThrow("SAV_DEPLOYMENT_EVIDENCE_CHANGED");
  });
  it("does not score an empty corpus or a superseded review", async () => {
    await expect(runReviewedSavRuleReplay("ugo@limova.ai")).rejects.toThrow("SAV_REPLAY_CORPUS_EMPTY");
    await createReviewedSavReplay(replayInput(), "ugo@limova.ai");
    await fixture.db.update(savProposalReviews).set({ isCurrent: false }).where(eq(savProposalReviews.id, reviewId));
    await expect(runReviewedSavRuleReplay("ugo@limova.ai")).rejects.toThrow("SAV_REPLAY_CORPUS_EMPTY");
  });
  it("records a gated promotion request as documentation only and invalidates outdated replays", async () => {
    const [message] = await fixture.db.select().from(savMessages).where(eq(savMessages.id, messageId));
    const [run] = await fixture.db.select().from(savAgentRuns).where(eq(savAgentRuns.id, runId));
    const [review] = await fixture.db.select().from(savProposalReviews).where(eq(savProposalReviews.id, reviewId));
    const [decision] = await fixture.db.select().from(savDecisions).where(eq(savDecisions.id, review.decisionId));
    const additional = Array.from({ length: 99 }, () => ({ messageId: crypto.randomUUID(), runId: crypto.randomUUID(), decisionId: crypto.randomUUID() }));
    await fixture.db.insert(savMessages).values(additional.map((a) => ({ ...message, id: a.messageId })));
    await fixture.db.insert(savAgentRuns).values(additional.map((a) => ({ ...run, id: a.runId, messageId: a.messageId })));
    await fixture.db.insert(savDecisions).values(additional.map((a) => ({ ...decision, id: a.decisionId, messageId: a.messageId, agentRunId: a.runId })));
    await fixture.db.insert(savProposalReviews).values(additional.map((a) => ({ ...review, id: crypto.randomUUID(), messageId: a.messageId, agentRunId: a.runId, decisionId: a.decisionId })));
    await createReviewedSavReplay(replayInput(), "ugo@limova.ai");
    await runReviewedSavRuleReplay("ugo@limova.ai");
    const data = await getSavV0Dashboard();
    expect(data.versions[0].gate.eligible).toBe(true);
    await recordSavDeploymentDecision({ snapshotHash: data.snapshotHash, versionId: data.versions[0].id, decision: "request_promotion", reason: "Preuves fictives suffisantes : décision documentaire uniquement" }, "ugo@limova.ai");
    expect((await getSavV0Dashboard()).decisions[0].decision).toBe("request_promotion");
    expect(await fixture.db.select().from(savActions)).toHaveLength(0);
    const [otherReview] = await fixture.db.select().from(savProposalReviews).where(eq(savProposalReviews.messageId, additional[0].messageId));
    await createReviewedSavReplay({ ...replayInput(), reviewId: otherReview.id }, "ugo@limova.ai");
    expect((await getSavV0Dashboard()).versions[0].gate.reasons).toContain("SAV_V0_REPLAY_REQUIRED");
    await runReviewedSavRuleReplay("ugo@limova.ai");
    expect((await getSavV0Dashboard()).versions[0].gate.eligible).toBe(true);
    await fixture.db.update(savAgentRuns).set({ dataOrigin: "simulation" });
    expect((await getSavV0Dashboard()).versions[0].gate.reasons).toContain("SAV_V0_REAL_DATA_REQUIRED");
  });
});
