import Link from "next/link";
import { UserButton } from "@clerk/nextjs";
import { Activity, BookOpen, ClipboardCheck, Gauge, GitBranch, GraduationCap, Inbox, ShieldCheck } from "lucide-react";
import type { ReactNode } from "react";
import type { StaffIdentity } from "@/lib/auth";
import { canCreateTraining, canManageProduction, staffRoleLabel } from "@/lib/access";
export function StudioShell({ staff, children }: { staff: StaffIdentity; children: ReactNode }) {
  return <div className="shell"><aside className="sidebar"><Link href="/studio" className="brand"><span className="brand-mark">C</span><span><strong>Studio Charly</strong><small>Apprentissage interne</small></span></Link><nav className="nav" aria-label="Navigation principale"><Link href="/studio"><Gauge size={17}/> Vue d’ensemble</Link>{canManageProduction(staff.role) && <Link href="/studio/sav"><Inbox size={17}/> SAV IA</Link>}<Link href="/studio/contenus"><BookOpen size={17}/> Contenus par agent</Link>{canManageProduction(staff.role) && <Link href="/studio/trame"><GitBranch size={17}/> Trame d’onboarding</Link>}{canCreateTraining(staff.role) && <Link href="/studio/entrainements"><GraduationCap size={17}/> Entraînements</Link>}{canManageProduction(staff.role) && <Link href="/studio/validations"><ShieldCheck size={17}/> Validations</Link>}<Link href="/studio/tests"><ClipboardCheck size={17}/> Qualité</Link>{canManageProduction(staff.role) && <Link href="/studio/sante"><Activity size={17}/> Santé</Link>}</nav><div className="staff-chip"><strong>{staff.name}</strong><br/><span>{staff.email}</span><div className="staff-account"><UserButton showName={false} appearance={{ elements: { userButtonTrigger: { width: "30px", height: "30px" } } }}/><span className="staff-role-label">{staffRoleLabel(staff.role)}</span></div></div></aside><main className="main"><div className="topline"><span className="eyebrow">Charly apprend en continu</span><span className="live-indicator"><i/> Base synchronisée</span></div>{children}</main></div>;
}
